[package]
name = "python_parser"
version = "0.1.0"
edition = "2024"

[dependencies]
rowan.workspace = true
rust-i18n.workspace = true
serde.workspace = true

[package.metadata.i18n]
available-locales = ["en", "zh_CN", "zh_HK"]
default-locale = "en"
